### ISSUE TITLE
Invitation to DocuActions

### ISSUE THREAD

**Issue by henrynewman** [DigiPie/kaya-folio#8]
Hello Evan Tay, I saw your [article ](https://evantay.com/blog/docusaurus-gh-action/) on your hardship with deploying Docusaurus to GitHub Pages. I have created  DocuActions which I contribute with other developers to create Docusaurus Actions to enable the community to generate documentation websites and deploy them using GitHub Actions. You can access it here - https://github.com/docuactions and the repo for GitHub Pages is https://github.com/docuactions/github-pages. Your contributions would be highly appreciated. 

Built by the Community for the Community.

**Comment by DigiPie** [comment]
Thanks for the invitation Henry, I'll take a look.
